name: rocket
channels:
  - pytorch
  - nvidia
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - _py-xgboost-mutex=2.0
  - alembic=1.7.5
  - anyio=3.5.0
  - anyqt=0.2.0
  - argon2-cffi=20.1.0
  - asttokens=2.0.5
  - atk-1.0=2.36.0
  - attrs=21.4.0
  - autopage=0.5.1
  - babel=2.9.1
  - backcall=0.2.0
  - baycomp=1.0.2
  - beautifulsoup4=4.11.1
  - blas=1.0
  - bleach=4.1.0
  - bottleneck=1.3.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2023.5.7
  - cachecontrol=0.13.0
  - cairo=1.16.0
  - catboost=1.2
  - certifi=2023.5.7
  - cffi=1.15.1
  - chardet=5.1.0
  - charset-normalizer=2.0.4
  - cliff=4.0.0
  - cmaes=0.8.2
  - cmd2=2.4.2
  - colorlog=5.0.1
  - commonmark=0.9.1
  - cryptography=37.0.1
  - cuda=11.6.1
  - cuda-cccl=11.6.55
  - cuda-command-line-tools=11.6.2
  - cuda-compiler=11.6.2
  - cuda-cudart=11.7.99
  - cuda-cudart-dev=11.6.55
  - cuda-cuobjdump=11.6.124
  - cuda-cupti=11.7.101
  - cuda-cuxxfilt=11.6.124
  - cuda-driver-dev=11.6.55
  - cuda-gdb=12.1.105
  - cuda-libraries=11.7.1
  - cuda-libraries-dev=11.6.1
  - cuda-memcheck=11.8.86
  - cuda-nsight=12.1.105
  - cuda-nsight-compute=12.1.1
  - cuda-nvcc=11.6.124
  - cuda-nvdisasm=12.1.105
  - cuda-nvml-dev=11.6.55
  - cuda-nvprof=12.1.105
  - cuda-nvprune=11.6.124
  - cuda-nvrtc=11.7.99
  - cuda-nvrtc-dev=11.6.124
  - cuda-nvtx=11.7.91
  - cuda-nvvp=12.1.105
  - cuda-runtime=11.7.1
  - cuda-samples=11.6.101
  - cuda-sanitizer-api=12.1.105
  - cuda-toolkit=11.6.1
  - cuda-tools=11.6.1
  - cuda-visual-tools=11.6.1
  - cudatoolkit=11.0.3
  - cycler=0.11.0
  - dbus=1.13.18
  - debugpy=1.5.1
  - decorator=5.1.1
  - defusedxml=0.7.1
  - deprecated=1.2.13
  - dictdiffer=0.9.0
  - docutils=0.20.1
  - dtw-python=1.1.10
  - entrypoints=0.4
  - et_xmlfile=1.1.0
  - executing=0.8.3
  - expat=2.4.9
  - ffmpeg=4.3.2
  - fftw=3.3.9
  - filelock=3.12.2
  - flit-core=3.6.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.13.1
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.25.0
  - freetype=2.11.0
  - fribidi=1.0.10
  - future=0.18.3
  - gdk-pixbuf=2.42.8
  - gds-tools=1.6.1.9
  - giflib=5.2.1
  - glib=2.69.1
  - gmp=6.2.1
  - gnutls=3.6.15
  - gobject-introspection=1.72.0
  - graphite2=1.3.14
  - graphviz=2.50.0
  - greenlet=1.1.1
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - gtk2=2.24.33
  - gts=0.7.6
  - h11=0.14.0
  - h2=4.1.0
  - harfbuzz=4.3.0
  - hpack=4.0.0
  - httpcore=0.17.3
  - httpx=0.24.1
  - hyperframe=6.0.1
  - icu=58.2
  - idna=3.4
  - importlib-metadata=4.11.3
  - importlib_metadata=4.11.3
  - importlib_resources=5.2.0
  - intel-openmp=2021.4.0
  - ipykernel=6.15.2
  - ipython=8.4.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.5
  - jaraco.classes=3.2.3
  - jedi=0.18.1
  - jeepney=0.8.0
  - jinja2=3.0.3
  - joblib=1.1.0
  - jpeg=9e
  - json5=0.9.6
  - jsonschema=4.16.0
  - jupyter=1.0.0
  - jupyter_client=7.3.5
  - jupyter_console=6.4.3
  - jupyter_core=4.11.1
  - jupyter_server=1.18.1
  - jupyterlab=3.4.4
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.15.2
  - jupyterlab_widgets=1.0.0
  - keyring=23.9.3
  - keyrings.alt=4.2.0
  - kiwisolver=1.4.2
  - krb5=1.19.2
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libclang=10.0.1
  - libcublas=11.10.3.66
  - libcublas-dev=11.9.2.110
  - libcufft=10.7.2.124
  - libcufft-dev=10.7.1.112
  - libcufile=1.7.0.149
  - libcufile-dev=1.6.1.9
  - libcurand=10.3.3.53
  - libcurand-dev=10.3.2.106
  - libcusolver=11.4.0.1
  - libcusparse=11.7.4.91
  - libcusparse-dev=11.7.2.124
  - libdeflate=1.8
  - libedit=3.1.20210910
  - libevent=2.1.12
  - libffi=3.3
  - libgcc-ng=11.2.0
  - libgd=2.3.3
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgomp=11.2.0
  - libiconv=1.16
  - libidn2=2.3.2
  - libllvm10=10.0.1
  - libllvm11=11.1.0
  - libnpp=11.7.4.75
  - libnpp-dev=11.6.3.124
  - libnvjpeg=11.8.0.2
  - libnvjpeg-dev=11.6.2.124
  - libpng=1.6.37
  - libpq=12.9
  - librsvg=2.54.4
  - libsodium=1.0.18
  - libstdcxx-ng=11.2.0
  - libtasn1=4.16.0
  - libtiff=4.4.0
  - libtool=2.4.6
  - libunistring=0.9.10
  - libuuid=1.0.3
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxcb=1.15
  - libxgboost=1.5.1
  - libxkbcommon=1.0.1
  - libxml2=2.9.14
  - libxslt=1.1.35
  - llvmlite=0.38.0
  - lockfile=0.12.2
  - lz4-c=1.9.3
  - mako=1.2.3
  - markupsafe=2.1.1
  - matplotlib=3.5.2
  - matplotlib-base=3.5.2
  - matplotlib-inline=0.1.6
  - mistune=0.8.4
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - more-itertools=9.1.0
  - mpmath=1.3.0
  - msgpack-python=1.0.3
  - munkres=1.1.4
  - nbclassic=0.3.5
  - nbclient=0.5.13
  - nbconvert=6.4.4
  - nbformat=5.5.0
  - nccl=2.12.12.1
  - ncurses=6.3
  - nest-asyncio=1.5.5
  - nettle=3.7.3
  - networkx=2.8.4
  - notebook=6.4.12
  - nsight-compute=2023.1.1.4
  - nspr=4.33
  - nss=3.74
  - numba=0.55.0
  - numexpr=2.8.3
  - numpy=1.21.5
  - numpy-base=1.21.5
  - openh264=2.1.1
  - openpyxl=3.0.9
  - openssl=1.1.1u
  - opentsne=0.6.1
  - optuna=3.0.2
  - orange-canvas-core=0.1.31
  - orange-widget-base=4.21.0
  - orange3=3.32.0
  - packaging=21.3
  - pandas=1.4.4
  - pandocfilters=1.5.0
  - pango=1.50.7
  - parso=0.8.3
  - patsy=0.5.2
  - pbr=5.6.0
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.2.0
  - pip=22.2.2
  - pixman=0.38.0
  - pkgutil-resolve-name=1.3.10
  - plotly=5.15.0
  - ply=3.11
  - prettytable=3.4.1
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.20
  - prompt_toolkit=3.0.20
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - py-xgboost=1.5.1
  - pycparser=2.21
  - pygments=2.11.2
  - pyopenssl=22.0.0
  - pyparsing=3.0.9
  - pyperclip=1.8.2
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
  - pyqtgraph=0.13.3
  - pyqtwebengine=5.15.7
  - pyrsistent=0.18.0
  - pysocks=1.7.1
  - python=3.8.13
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.2
  - python-graphviz=0.20.1
  - python-louvain=0.16
  - python_abi=3.8
  - pytorch=2.0.1
  - pytorch-cuda=11.7
  - pytorch-mutex=1.0
  - pytz=2022.1
  - pyyaml=6.0
  - pyzmq=23.2.0
  - qasync=0.24.0
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtconsole=5.3.2
  - qtpy=2.2.0
  - qtwebkit=5.212
  - readline=8.1.2
  - requests=2.28.1
  - scikit-base=0.4.6
  - scikit-learn=1.1.2
  - scipy=1.7.3
  - seaborn=0.11.2
  - secretstorage=3.3.3
  - send2trash=1.8.0
  - serverfiles=0.3.0
  - setuptools=63.4.1
  - sip=6.6.2
  - six=1.16.0
  - sktime=0.20.0
  - sniffio=1.2.0
  - soupsieve=2.3.1
  - sqlalchemy=1.4.39
  - sqlite=3.39.3
  - stack_data=0.2.0
  - statsmodels=0.13.2
  - stevedore=4.0.0
  - sympy=1.12
  - tbb=2021.6.0
  - tenacity=8.2.2
  - terminado=0.13.1
  - testpath=0.6.0
  - threadpoolctl=2.2.0
  - tk=8.6.12
  - toml=0.10.2
  - torchaudio=2.0.2
  - torchtriton=2.0.0
  - torchvision=0.15.2
  - tornado=6.2
  - tqdm=4.64.1
  - traitlets=5.1.1
  - typing_extensions=4.7.1
  - urllib3=1.26.11
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=0.58.0
  - wheel=0.37.1
  - widgetsnbextension=3.5.2
  - wrapt=1.14.1
  - x264=1!161.3030
  - xgboost=1.5.1
  - xlrd=2.0.1
  - xlsxwriter=3.1.2
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.2
  - xorg-libx11=1.7.2
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.6
  - yaml=0.2.5
  - zeromq=4.3.4
  - zipp=3.8.0
  - zlib=1.2.12
  - zstd=1.5.2
